version: "{build}"

environment:
  matrix:
  - GENERATOR: Visual Studio 14 2015
  - GENERATOR: Visual Studio 14 2015 Win64
  - GENERATOR: Visual Studio 12 2013
  - GENERATOR: Visual Studio 12 2013 Win64

branches:
  except:
    - /^(wip\/)?(travis|osx|mingw|ipp)(\-.+)?$/

configuration: Debug

install:
  - git submodule update --init --recursive

before_build:
  - mkdir build
  - cd build
  - cmake -G "%GENERATOR%" -DCMAKE_BUILD_TYPE=%CONFIGURATION% -DCMAKE_INSTALL_PREFIX=./out -DENABLE_DENSITY=no -DENABLE_GIPFELI=no ..

build_script: cmake --build . --target install --config %CONFIGURATION%

test_script: ctest -V --interactive-debug-mode 0 --timeout 600 -C %CONFIGURATION% .
