language: c
os:
  - linux
#  - osx
env:
  - COMPILER=gcc-5 BUILD_TYPE=regular
  - COMPILER=gcc-5 BUILD_TYPE=asan
#  - COMPILER=gcc-5 BUILD_TYPE=ubsan
#  - COMPILER=gcc-5 BUILD_TYPE=tsan
  - COMPILER=clang BUILD_TYPE=regular
  - COMPILER=gcc-4.8 BUILD_TYPE=regular
before_install:
 - ./.travis.sh deps
script: ./.travis.sh build && ./.travis.sh test
# notifications:
#   irc:
#     channels:
#       - "chat.freenode.net#squash"
#     on_success: change
#     on_failure: always
