language: c
os:
  - linux
#  - osx
compiler:
  - gcc
  - clang
before_install:
 - ./.travis.sh deps
script: ./.travis.sh build && ./.travis.sh test
# notifications:
#   irc:
#     channels:
#       - "chat.freenode.net#squash"
#     on_success: change
#     on_failure: always
