language: c
compiler:
  - gcc
  - clang
before_install:
 - sudo apt-get update -qq
 # Remember to keep this synced with build-deps.catalog
 - sudo apt-get install -qq gcc g++ autoconf automake libtool libltdl-dev libglib2.0-dev libbz2-dev liblzma-dev liblzo2-dev libsnappy-dev zlib1g-dev
script: ./autogen.sh && make && make check
notifications:
  irc:
    channels:
      - "chat.freenode.net#squash"
    on_failure: always
